### ISSUE TITLE
how to generate 'summary.pkl'

### ISSUE THREAD

**Issue by SinDongHwan** [tsujuifu/pytorch_vsum-ptr-gan#3]

**Comment by tsujuifu** [comment]
Hi, SinDongHwan.
The 'summary.pkl' is generated from the ground truth of the original dataset.

**Comment by SinDongHwan** [comment]
thank you!!
i've just found summe dataset. 
summe dataset don't have a "summary.pkl"
i will try to run with ytsum dataset.

**Comment by JuJiHyun** [comment]
> thank you!!
> i've just found summe dataset.
> summe dataset don't have a "summary.pkl"
> i will try to run with ytsum dataset.

Did you solved the problem?
How did you create summary.pkl?
thank you
