### ISSUE TITLE
YouTube Dataset (Preprocessed) can't open

### ISSUE THREAD

**Issue by harvestlamb** [tsujuifu/pytorch_vsum-ptr-gan#7]
hi~
YouTube Dataset (Preprocessed) can't open，
could you upload a new Preprocessed Dataset  in Google drive？
thanks you！

**Comment by SinDongHwan** [comment]
@harvestlamb 

Hi, harvestlamb!!
I uploaded Youtube Dataset on my one-drive.
I think this is preprocessed dataset.
[Download link](https://1drv.ms/u/s!Au4J1yd2Q9NvguQ73DGawBbXoYc9AQ?e=2a4ZHY)

Good luck~!!

**Comment by harvestlamb** [comment]
> @harvestlamb
> 
> Hi, harvestlamb!!
> I uploaded Youtube Dataset on my one-drive.
> I think this is preprocessed dataset.
> [Download link](https://1drv.ms/u/s!Au4J1yd2Q9NvguQ73DGawBbXoYc9AQ?e=2a4ZHY)
> 
> Good luck~!!

thank you very much!
